In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Regresión Ridge ##

In [2]:
data = pd.read_csv('DataSets/modelo_de_clientes/Customer Churn Model.txt')
data.head()

State  Account Length  Area Code     Phone Int'l Plan VMail Plan  \
0    KS             128        415  382-4657         no        yes   
1    OH             107        415  371-7191         no        yes   
2    NJ             137        415  358-1921         no         no   
3    OH              84        408  375-9999        yes         no   
4    OK              75        415  330-6626        yes         no   

   VMail Message  Day Mins  Day Calls  Day Charge  ...  Eve Calls  Eve Charge  \
0             25     265.1        110       45.07  ...         99       16.78   
1             26     161.6        123       27.47  ...        103       16.62   
2              0     243.4        114       41.38  ...        110       10.30   
3              0     299.4         71       50.90  ...         88        5.26   
4              0     166.7        113       28.34  ...        122       12.61   

   Night Mins  Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
0       244.7           91         11.01       10.0           3         2.70   
1       254.4          103         11.45       13.7           3         3.70   
2       162.6          104          7.32       12.2           5         3.29   
3       196.9           89          8.86        6.6           7         1.78   
4       186.9          121          8.41       10.1           3         2.73   

   CustServ Calls  Churn?  
0               1  False.  
1               1  False.  
2               0  False.  
3               2  False.  
4               3  False.  

[5 rows x 21 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   State           3333 non-null   object 
 1   Account Length  3333 non-null   int64  
 2   Area Code       3333 non-null   int64  
 3   Phone           3333 non-null   object 
 4   Int'l Plan      3333 non-null   object 
 5   VMail Plan      3333 non-null   object 
 6   VMail Message   3333 non-null   int64  
 7   Day Mins        3333 non-null   float64
 8   Day Calls       3333 non-null   int64  
 9   Day Charge      3333 non-null   float64
 10  Eve Mins        3333 non-null   float64
 11  Eve Calls       3333 non-null   int64  
 12  Eve Charge      3333 non-null   float64
 13  Night Mins      3333 non-null   float64
 14  Night Calls     3333 non-null   int64  
 15  Night Charge    3333 non-null   float64
 16  Intl Mins       3333 non-null   float64
 17  Intl Calls      3333 non-null   i

In [4]:
x = ['Night Mins', 'Night Calls']
x = np.array(data[x])
y = ['Night Charge']
y = np.array(data[y])

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
scaler = StandardScaler()

In [7]:
x = scaler.fit_transform(x)
y = scaler.fit_transform(y)

In [8]:
print(x)

[[ 0.86674322 -0.46549436]
 [ 1.05857074  0.14782467]
 [-0.75686906  0.19893459]
 ...
 [-0.1774313  -0.46549436]
 [-1.21962822  1.88556193]
 [ 0.80148231 -1.18103324]]


In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [11]:
from sklearn.linear_model import Ridge

In [12]:
ridge = Ridge(alpha = 0.1)

In [13]:
ridge.alpha

0.1

In [14]:
ridge.fit(x_train, y_train)

Ridge(alpha=0.1)

In [15]:
ridge.intercept_, ridge.coef_

(array([2.0636922e-06]), array([ 9.99959631e-01, -3.26293008e-05]))

In [16]:
y_pred = ridge.predict(x_test)

In [17]:
from sklearn.metrics import r2_score

In [18]:
r2_score(y_test, y_pred)

0.9999984508855456

## Refresipon de Lasso ##

In [19]:
from sklearn.linear_model import Lasso

In [20]:
lasso = Lasso(alpha = 0.1)

In [21]:
lasso.fit(x_train, y_train)

Lasso(alpha=0.1)

In [22]:
lasso.intercept_, lasso.coef_

(array([0.00062136]), array([0.89995506, 0.        ]))

In [23]:
y_pred = lasso.predict(x_test)

In [24]:
r2_score(y_test, y_pred)

0.9899783373214941

In [25]:
from physics.linear_regression import Ridge

In [26]:
rid = Ridge()

In [27]:
rid.fit(x_train, y_train)

In [28]:
rid.intercept, rid.coef

(array([2.06361478e-06]),
 array([[ 9.99959631e-01],
        [-3.26293017e-05]]))

In [29]:
y_pred_rid = rid.predict(x_test)

In [30]:
r2_score(y_test, y_pred_rid)

0.9999984508855472

In [31]:
from physics.linear_regression import Lasso

In [32]:
las = Lasso(lil_batch=True)

In [33]:
las.fit(x_train, y_train)

In [34]:
las.intercept, las.coef

(None, None)

In [35]:
y_pred_las = las.predict(x_test)

In [36]:
r2_score(y_test, y_pred_las)

-0.19760804373538599