In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('DataSets/usuarios.csv')
data.head(20)

duracion  paginas  acciones  valor  clase
0      7.000        2         4      8      2
1     21.000        2         6      6      2
2     57.000        2         4      4      2
3    101.000        3         6     12      2
4    109.000        2         6     12      2
5    125.000        5        10     20      2
6    133.000        2         2      4      2
7    162.000        2         6     12      2
8    170.000        2         4      8      2
9    217.000        2         6      6      2
10   266.000        2         6     12      2
11   335.000        4        12     24      2
12   553.000        4        12     24      2
13   798.000        5        15     15      2
14   872.000        2         6      6      2
15     1.105        2         4      8      2
16     2.091        5         5      5      2
17    21.000        2         4     12      1
18    33.000        2         8     48      1
19    49.000        2         8     32      1

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   duracion  170 non-null    float64
 1   paginas   170 non-null    int64  
 2   acciones  170 non-null    int64  
 3   valor     170 non-null    int64  
 4   clase     170 non-null    int64  
dtypes: float64(1), int64(4)
memory usage: 6.8 KB


In [4]:
len(np.unique(data['clase']))

3

In [5]:
data.isnull().sum()

duracion    0
paginas     0
acciones    0
valor       0
clase       0
dtype: int64

In [6]:
_list = [x for x in data.columns if x != 'clase']

In [7]:
x = np.array(data[_list])
y = np.array(data[['clase']])

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()

In [10]:
x = scaler.fit_transform(x)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
log = LogisticRegression()

In [15]:
log.fit(x_train, y_train.ravel())

LogisticRegression()

In [16]:
y_pred = log.predict(x_test)

In [17]:
y_pred

array([2, 2, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0,
       2, 0, 2, 2, 0, 0, 1, 2, 0, 0, 2, 0])

In [18]:
log.intercept_, log.coef_

(array([ 0.96700383,  0.27183656, -1.23884038]),
 array([[-0.35450681, -0.41970737,  1.18715026,  0.87355429],
        [ 0.17344305, -0.10049277, -0.91363516,  2.10191145],
        [ 0.18106376,  0.52020014, -0.2735151 , -2.97546574]]))

In [19]:
from sklearn.metrics import confusion_matrix, classification_report

In [20]:
confusion_matrix(y_test, y_pred)

array([[15,  1,  4],
       [ 3,  1,  0],
       [ 0,  0, 10]])

In [21]:
print(classification_report(y_test, y_pred)) # Mdelo malísimo por culpa de la falta de datos

              precision    recall  f1-score   support

           0       0.83      0.75      0.79        20
           1       0.50      0.25      0.33         4
           2       0.71      1.00      0.83        10

    accuracy                           0.76        34
   macro avg       0.68      0.67      0.65        34
weighted avg       0.76      0.76      0.75        34



In [22]:
from physics.logisctic_regression import LogisticRegression

In [23]:
rl = LogisticRegression(tol = 1e-3)

In [24]:
rl.fit(x_train, y_train)

In [25]:
y_pred = rl.predict(x_test)

In [26]:
rl.intercept, rl.coef

(array([ 0.99713463,  0.27106449, -1.26819912]),
 array([[-0.39060002, -0.51362703,  1.58117918,  0.66926768],
        [ 0.20291702, -0.12996793, -0.96077893,  2.18736724],
        [ 0.187683  ,  0.64359497, -0.62040025, -2.85663492]]))

In [27]:
y_pred

array([[0, 0, 1],
       [1, 0, 1],
       [1, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 1, 0],
       [1, 1, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 1, 0],
       [0, 0, 1],
       [1, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 0, 1],
       [1, 1, 0],
       [1, 0, 1],
       [1, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 1, 0],
       [0, 0, 1],
       [1, 0, 0]])